/**
	*  ESLint → Rules → Suggestions
	*  @link https://eslint.org/docs/latest/rules/#suggestions Documentation
 */

module.exports = {
	"rules": {
		"accessor-pairs": "error",
		"arrow-body-style": ["error", "always"],
		"camelcase": ["error", {
			"properties": "always",
			"ignoreImports": false,
			"ignoreGlobals": false
		}],
		"capitalized-comments": ["error", "always"],
		"class-methods-use-this": "error",
		"complexity": "warn",
		"consistent-return": "error",
		"consistent-this": ["error", "self"],
		"curly": "error",
		"default-case": "error",
		"default-case-last": "error",
		"default-param-lastn": "error",


		"dot-notation": ["error", {
			"allowPattern": "^[a-z]+(_[a-z]+)+$"
		}],
		"eqeqeq": ["error", "always"],
		"func-style": ["error", "expression"],
		"guard-for-in": "error",
		"id-length": ["error", {
			"min": 3,
			"properties": "always",
			"exceptions": ["x", "i", "y", "z", "id"]
		}],
		"init-declarations": ["error", "always"],
		"logical-assignment-operators": ["error", "always"],
		"max-classes-per-file": ["warn", 1],
		"max-depth": ["warn", 3],
		"max-nested-callbacks": ["warn", 3],
		"max-params": ["warn", 3],
		"multiline-comment-style": ["error", "starred-block"],
		"new-cap": ["error", {
			"capIsNew": true,
			"newIsCap": true,
			"newIsCapExceptions": ["events"],
			"properties": false
		}],
		"no-alert": "error",
		"no-bitwise": "error",
		"no-case-declarations": "error",
		"no-confusing-arrow": "error",
		"no-console": "warn",
		"no-continue": "error",
		"no-delete-var": "error",
		"no-div-regex": "error",
		"no-else-return": ["error", { "allowElseIf": true }],
		"no-empty-function": "error",
		"no-empty-static-block": "error",
		"no-eq-null": "error",
		"no-eval": "error",
		"no-extend-native": "error",
		"no-extra-bind": "error",
		"no-extra-label": "error",
		"no-floating-decimal": "error",
		"no-implicit-coercion": "error",
		"no-implied-eval": "error",
		"no-inline-comments": "error",
		"no-invalid-this": "error",
		"no-iterator": "error",
		"no-label-var": "error",
		"no-labels": "error",
		"no-lone-blocks": "error",
		"no-lonely-if": "error",
		"no-loop-func": "error",
		"no-magic-numbers": ["error", {
			"ignore": [1],
			"ignoreArrayIndexes": true,
			"ignoreClassFieldInitialValues": true,
			"enforceConst": true,
		}],
		"no-mixed-operators": "error",
		"no-multi-assign": "error",
		"no-multi-str": "error",
		"no-negated-condition": "error",
		"no-nested-ternary": "error",
		"no-new": "error",
		"no-new-func": "error",
		"no-new-object": "error",
		"no-new-wrappers": "error",
		"no-octal": "error",
		"no-octal-escape": "error",
		"no-param-reassign": "error",
		"no-plusplus": "error",
		"no-proto": "error",
		"no-return-assign": "error",
		"no-return-await": "error",
		"no-script-url": "error",
		"no-sequences": "error",
		"no-shadow": "error",
		"no-throw-literal": "error",
		"no-undef-init": "error",
		"no-undefined": "error",
		"no-underscore-dangle": ["error", { "allowAfterThis": true }],
		"no-unneeded-ternary": "error",
		"no-unused-expressions": ["error", { "allowTernary": true }],
		"no-useless-call": "error",
		"no-useless-computed-key": "error",
		"no-useless-concat": "error",
		"no-useless-constructor": "error",
		"no-useless-rename": "error",
		"no-useless-return": "error",
		"no-var": "error",
		"no-void": "error",
		"one-var": ["error", "never"],
		"one-var-declaration-per-line": ["error", "always"],
		"operator-assignment": ["error", "always"],
		"prefer-arrow-callback": "error",
		"prefer-const": "error",
		"prefer-numeric-literals": "error",
		"prefer-object-has-own": "error",
		"prefer-object-spread": "error",
		"prefer-promise-reject-errors": "error",
		"prefer-spread": "error",
		"prefer-template": "error",
		"quote-props": ["error", "consistent-as-needed", {
			"keywords": true
		}],
		"radix": ["error", "as-needed"],
		"sort-imports": ["error", {
			"ignoreCase": false,
			"ignoreDeclarationSort": false,
			"ignoreMemberSort": false,
			"memberSyntaxSortOrder": ["none", "all", "multiple", "single"],
			"allowSeparatedGroups": false
		}],
		"sort-keys": ["error", "asc", {
			"caseSensitive": true,
			"natural": true,
			"minKeys": 2
		}],
		"sort-vars": "error",
		"spaced-comment": ["error", "always"],
		"symbol-description": "error",
		"vars-on-top": "error",
		"yoda": "error"
	}
};
