#!/usr/bin/env zsh 

# --------------------------------------------------------------------------
#   ZSH → Helpers → yt-dlp
#   @see https://bit.ly/2AD7bYb
# --------------------------------------------------------------------------

function yt-botw {
	yt-dlp --cookies-from-browser="brave" $1 -o '$HOME/Desktop/botw/%(title)s/%(title)s.%(ext)s'
}

function yt-flac-single {
	yt-dlp --cookies-from-browser="brave" -f "bestaudio/best" -ciw -o "%(title)s.%(ext)s" -v --extract-audio --audio-format flac $1;
}

function yt-flac-playlist {
	yt-dlp --cookies-from-browser="brave" -f "bestaudio/best" -ciw -o "%(title)s.%(ext)s" -v --extract-audio --audio-format flac --yes-playlist $1;
}

function yt-flac {
	yt-flac-single $1;
}
