#!/usr/bin/env bash
# --------------------------------------------------------------------------
#   ZSH → OhMyZSH → Plugins → ZSH Autosuggestions
#   @see https://github.com/zsh-users/zsh-autosuggestions
# --------------------------------------------------------------------------

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=0,bg=51,bold,underline"
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_USE_ASYNC=TRUE