#!/usr/bin/env zsh
# --------------------------------------------------------------------------
#   ZSH → Colors
#   Creates color and text-formatting settings.
# --------------------------------------------------------------------------


#   Text Formatting
# ------------------------------------------------------------

# Creates bold-face text.
bold=$(tput bold);

# Reset text back to normal.
reset=$(tput sgr0);

# Creates underlined text.
underline=$(tput sgr 0 1);


#   Colors → Foreground
#   Sets text color.
# ------------------------------------------------------------

black=$(tput setaf 0);
blue=$(tput setaf 4);
cyan=$(tput setaf 6);
green=$(tput setaf 2);
magenta=$(tput setaf 5);
purple=$(tput setaf 171);
red=$(tput setaf 1);
white=$(tput setaf 7);
yellow=$(tput setaf 3);


#   Colors → Background
#   Sets background color.
# ------------------------------------------------------------

bg_black=$(tput setab 0);
bg_blue=$(tput setab 4);
bg_cyan=$(tput setab 6);
bg_green=$(tput setab 2);
bg_magenta=$(tput setab 5);
bg_purple=$(tput setab 171);
bg_red=$(tput setab 1);
bg_white=$(tput setab 7);
bg_yellow=$(tput setab 3);
