#!/usr/bin/env zsh
# --------------------------------------------------------------------------
#   ZSH → CLI → Fun
# --------------------------------------------------------------------------

# Playball
# @see https://github.com/paaatrick/playball
alias watch-baseball='playball';
alias baseball-game='playball';
