#!/usr/bin/env zsh 

# --------------------------------------------------------------------------
#   ZSH → CLI → youtube-dl
#   @see https://bit.ly/2AD7bYb
# --------------------------------------------------------------------------

function yt-botw {
	youtube-dl $1 -o '$HOME/Desktop/botw/%(title)s/%(title)s.%(ext)s'
}

function yt-flac-single {
	youtube-dl -f "bestaudio/best" -ciw -o "%(title)s.%(ext)s" -v --extract-audio --audio-format flac $1;
}

function yt-flac-playlist {
	youtube-dl -f "bestaudio/best" -ciw -o "%(title)s.%(ext)s" -v --extract-audio --audio-format flac --yes-playlist $1;
}

function yt-flac {
	yt-flac-single $1;
}
