#!/usr/bin/env zsh
# --------------------------------------------------------------------------
#   ZSH → CLI → NGINX
# --------------------------------------------------------------------------

# View error log.
alias nginx-get-errors='tail /var/log/nginx/error.log';
