#!/usr/bin/env zsh
# --------------------------------------------------------------------------
#   Shell::CLI::PHP
# --------------------------------------------------------------------------
#   @see https://www.drupal.org/docs/develop/coding-standards/list-of-sql-reserved-words
#   @note [PROGRAM]-[VERB]-[OPTIONAL SECOND NOUN]
# --------------------------------------------------------------------------

# Start a PHP server from a directory, optionally specifying the port
# (Requires PHP 5.4.0+.)
function php-init-server() {
	local port="${1:-4000}";
	local ip=$(ipconfig getifaddr en1);
	sleep 1 && open "http://${ip}:${port}/" &
	php -S "${ip}:${port}";
}

# View error log.
alias php-get-errors='tail /var/log/php/error.log';
